### ISSUE TITLE
Error with missing dependency while trying to run the extension in Keycloak 21.0.2

### ISSUE THREAD

**Issue by pcibraro** [vymalo/keycloak-webhook#3]
The extension is throwing this error -> Could not send webhook: java.lang.NoClassDefFoundError: com/google/gson/GsonBuilder. It was compiled with JDK 17. Have you seen that error before ?

**Comment by stephane-segning** [comment]
Ok let me look at this

**Comment by stephane-segning** [comment]
Ok, found it. You used the wrong probably. Try using the jar ending with `-all.jar`.
